stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed_data.csv
    outs:
      - models/model.pkl
    metrics:
      - metrics.json

  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
      - src/evaluate_model.py
      - models/model.pkl
      - data/test_data.csv
    metrics:
      - metrics.json
